require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ContactListsController do

  # This should return the minimal set of attributes required to create a valid
  # ContactList. As you add validations to ContactList, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "participant_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ContactListsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all contact_lists as @contact_lists" do
      contact_list = ContactList.create! valid_attributes
      get :index, {}, valid_session
      assigns(:contact_lists).should eq([contact_list])
    end
  end

  describe "GET show" do
    it "assigns the requested contact_list as @contact_list" do
      contact_list = ContactList.create! valid_attributes
      get :show, {:id => contact_list.to_param}, valid_session
      assigns(:contact_list).should eq(contact_list)
    end
  end

  describe "GET new" do
    it "assigns a new contact_list as @contact_list" do
      get :new, {}, valid_session
      assigns(:contact_list).should be_a_new(ContactList)
    end
  end

  describe "GET edit" do
    it "assigns the requested contact_list as @contact_list" do
      contact_list = ContactList.create! valid_attributes
      get :edit, {:id => contact_list.to_param}, valid_session
      assigns(:contact_list).should eq(contact_list)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ContactList" do
        expect {
          post :create, {:contact_list => valid_attributes}, valid_session
        }.to change(ContactList, :count).by(1)
      end

      it "assigns a newly created contact_list as @contact_list" do
        post :create, {:contact_list => valid_attributes}, valid_session
        assigns(:contact_list).should be_a(ContactList)
        assigns(:contact_list).should be_persisted
      end

      it "redirects to the created contact_list" do
        post :create, {:contact_list => valid_attributes}, valid_session
        response.should redirect_to(ContactList.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved contact_list as @contact_list" do
        # Trigger the behavior that occurs when invalid params are submitted
        ContactList.any_instance.stub(:save).and_return(false)
        post :create, {:contact_list => { "participant_id" => "invalid value" }}, valid_session
        assigns(:contact_list).should be_a_new(ContactList)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ContactList.any_instance.stub(:save).and_return(false)
        post :create, {:contact_list => { "participant_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested contact_list" do
        contact_list = ContactList.create! valid_attributes
        # Assuming there are no other contact_lists in the database, this
        # specifies that the ContactList created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ContactList.any_instance.should_receive(:update_attributes).with({ "participant_id" => "1" })
        put :update, {:id => contact_list.to_param, :contact_list => { "participant_id" => "1" }}, valid_session
      end

      it "assigns the requested contact_list as @contact_list" do
        contact_list = ContactList.create! valid_attributes
        put :update, {:id => contact_list.to_param, :contact_list => valid_attributes}, valid_session
        assigns(:contact_list).should eq(contact_list)
      end

      it "redirects to the contact_list" do
        contact_list = ContactList.create! valid_attributes
        put :update, {:id => contact_list.to_param, :contact_list => valid_attributes}, valid_session
        response.should redirect_to(contact_list)
      end
    end

    describe "with invalid params" do
      it "assigns the contact_list as @contact_list" do
        contact_list = ContactList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ContactList.any_instance.stub(:save).and_return(false)
        put :update, {:id => contact_list.to_param, :contact_list => { "participant_id" => "invalid value" }}, valid_session
        assigns(:contact_list).should eq(contact_list)
      end

      it "re-renders the 'edit' template" do
        contact_list = ContactList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ContactList.any_instance.stub(:save).and_return(false)
        put :update, {:id => contact_list.to_param, :contact_list => { "participant_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested contact_list" do
      contact_list = ContactList.create! valid_attributes
      expect {
        delete :destroy, {:id => contact_list.to_param}, valid_session
      }.to change(ContactList, :count).by(-1)
    end

    it "redirects to the contact_lists list" do
      contact_list = ContactList.create! valid_attributes
      delete :destroy, {:id => contact_list.to_param}, valid_session
      response.should redirect_to(contact_lists_url)
    end
  end

end
